計算処理部分(calculator)の作成
RikitoNoto/PythonCalculator pull request #7
Opened 2021-06-17 12:51 UTC by kanta-wk

# 計算処理の作成
計算式(サブdisplay)の表示と計算処理部の作成。

## 作成ファイル
- src/Calculator.py
- tests/test_Calculator.py

| 定数 | 内容 |
| :-- | :-: |
| PLUS | 0 (+) |
| SUB | 1 (-) |
| MULTI | 2 (×) |
| DIVI | 3 (÷) |

| 変数 | 内容 |
| :-- | :-: |
| left_value | 左辺 |
| right_value | 右辺 |
| operator | 演算子 |
| formula | 計算式(サブdisplay) |

| 関数 | 内容 |
| :-- | :-: |
| add | 足し算 |
| sub | 引き算 |
| multi | 掛け算 |
| divi | 割り算 |
| calculate | operatorの値によって実行する式を変化させ、計算結果を返す。 |
| operator_char | operatorにあった演算子(+,-,×,÷)を返す。 |

2021-06-17 13:24 UTC, RikitoNoto requested changes
- ソースコード内にコメントが少ないように感じます。sphinxでドキュメント出力できるようコメントの追加をお願いします。
- 桁数が多くなった際にGUIでは指数表記が欲しくなると思います。そのため、calculateメソッドの指数を返すパターンのメソッドの作成をお願いします。
- masterブランチに対してコンフリクトが発生しているようですので、解消をお願いします。

2021-06-17 13:24 UTC, RikitoNoto commented on src/Calculator.py
> +        if self.__operator==0:
マジックナンバーはやめましょう

2021-06-17 13:24 UTC, RikitoNoto commented on src/Calculator.py
> +            pass
例外を発生させ、このクラスの利用者に予期せぬ結果を知らせましょう。

2021-06-17 13:24 UTC, RikitoNoto commented on src/Calculator.py
> +        return result
__right_valueが0の時の例外補足をこのクラスでできないでしょうか。
例えば、0割が発生した時にエラーメッセージの文字列を返すようにする等。

2021-06-17 13:24 UTC, RikitoNoto commented on src/Calculator.py
> +        else:
__operatorのセッターにバリデーションをかけるか、ここでelseに例外を発生させるようにしないと__operatorに予期せぬ値が入っていた時に、クラス利用者はバグに気がつかなかったり、結果がおかしくなったりしないでしょうか。

2021-06-17 13:24 UTC, RikitoNoto commented on src/Calculator.py
> +        return  str(self.__left_value)+str(self.operator_char())+str(self.__right_value)+"="
string.formatメソッドを使用する方が綺麗に見えそうです。

2021-06-17 13:24 UTC, RikitoNoto commented on src/Calculator.py
> +    DIVI = 3
__operatorのバリデーションを考えると、このクラスはIntEnumを継承しオペレータ定数を列挙体かつ値の自動設定(autoメソッド)にした方がスムーズかもしれません。
(オペレータの数+1個の定数を宣言し、追加した余分な定数値以下であることをセッターでチェックするイメージです。)

2021-06-20 06:12 UTC, RikitoNoto requested changes

2021-06-20 06:12 UTC, RikitoNoto commented on src/Calculator.py
> +        return  str(self.__left_value)+str(self.operator_char())+str(self.__right_value)+"="
formula はright_valueが存在しない時も動作するようにするのと、=を削除できないでしょうか。
演算子ボタンが入力された時にサブディスプレイに　"123+"　のように現在の計算内容がわかるように表示したいです。

2021-06-21 05:19 UTC, kanta-wk commented on src/Calculator.py
> +            pass
ご指摘ありがとうございます。
改善させていただきます。

2021-06-21 05:19 UTC, kanta-wk commented on src/Calculator.py
> +    DIVI = 3
提案ありがとうございます。
確認してみます。

2021-06-21 05:19 UTC, kanta-wk commented on src/Calculator.py
> +        if self.__operator==0:
ご指摘していただきありがとうございます
修正しておきます。

2021-06-21 05:19 UTC, kanta-wk commented on src/Calculator.py
> +        return result
ご指摘していただきありがとうございます
変更しておきます。

2021-06-21 05:19 UTC, kanta-wk commented on src/Calculator.py
> +        else:
ご指摘していただきありがとうございます
おかしくなってしまうので修正させていただきます。

2021-06-21 05:19 UTC, kanta-wk commented on src/Calculator.py
> +        return  str(self.__left_value)+str(self.operator_char())+str(self.__right_value)+"="
ご提案ありがとうございます。
変更しておきます。

2021-06-21 05:19 UTC, kanta-wk commented on src/Calculator.py
> +        return  str(self.__left_value)+str(self.operator_char())+str(self.__right_value)+"="
ご指摘ありがとうございます

指摘内容通り修正しておきます。

2021-06-25 20:33 UTC, kanta-wk commented
> * ソースコード内にコメントがあります。
> * 桁数がななったりにGUIは指数関数が欲しこと一致を計算します。結果を計算します。
> * masterブランチ統一コンフリクトガシリとデスので、ブランチをボタンシます。



> * ソースコード内にコメントが少ないように感じます。sphinxでドキュメント出力できるようコメントの追加をお願いします。

→ソースコード内にコメント追加してわかりやすくしました。ご確認ください。

> * 桁数が多くなった際にGUIでは指数表記が欲しくなると思います。そのため、calculateメソッドの指数を返すパターンのメソッドの作成をお願いします。

→指数関数(index)を作成し、calculateを指数に変換するようにしました。ご確認ください。

> * masterブランチに対してコンフリクトが発生しているようですので、解消をお願いします。

2021-06-25 20:52 UTC, kanta-wk commented on src/Calculator.py
> +        return  str(self.__left_value)+str(self.operator_char())+str(self.__right_value)+"="
try、except関数にてright_valueがなくても動作するようにし、right_valueがなかった場合、例外を発生させるようにしました。
表示についても"="箇所を削除して、right_valueがなくても"123+"と出力できるようにしました。

2021-06-25 21:12 UTC, kanta-wk commented on src/Calculator.py
> +        return  str(self.__left_value)+str(self.operator_char())+str(self.__right_value)+"="
{ }.format(str(  ))を使用して分かりやすく、見た目もよくなりました。
ご確認ください。

2021-06-25 22:47 UTC, kanta-wk commented on src/Calculator.py
> +        if self.__operator==0:
0〜3のそれぞれの演算子名に変更しました。

【例】
0: PLUS

2021-06-25 22:51 UTC, kanta-wk commented on src/Calculator.py
> +        return result
DIVI関数内に
 
right_valueが0だった場合、
0 で割ることはできません。と文字列を返すようにしました。

2021-06-27 06:11 UTC, merged